/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui.Ngo;

import Funding.Donation.Donation;
import Funding.FundManager.FundManager;
import Ngo.Budget.Budget;
import System.Directories.DB4OUtil;
import System.Directories.MainSystem;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author megha
 */
public class FundManagerWorkspace extends javax.swing.JPanel {

    /**
     * Creates new form FundManagerWorkspace
     */
    private JPanel cardPanel;
    private FundManager fundManager;
    private MainSystem system;
    private DB4OUtil dB4OUtil;
    private final String FILENAME = "ProjectDataBank.db4o";
    
    public FundManagerWorkspace(FundManager fundManager,JPanel cardPanel, MainSystem system,DB4OUtil dB4OUtil ) {
        initComponents();
        this.fundManager = fundManager;
        this.cardPanel = cardPanel;
        this.system = system;
        this.dB4OUtil = dB4OUtil;
        populatePublicFund();
        initializeBud();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPaneFundManager = new javax.swing.JSplitPane();
        panelControl = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnBudget = new javax.swing.JButton();
        btnFund = new javax.swing.JButton();
        panelWork = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        lblTitle2 = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        panelPublicFund = new javax.swing.JPanel();
        ScrollPane = new javax.swing.JScrollPane();
        tablePublicFund = new javax.swing.JTable();
        lblTitle3 = new javax.swing.JLabel();
        panelBudget = new javax.swing.JPanel();
        lblTitle8 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblEducation = new javax.swing.JLabel();
        txtEducation = new javax.swing.JTextField();
        lblHealth = new javax.swing.JLabel();
        txtHealth = new javax.swing.JTextField();
        lblFood = new javax.swing.JLabel();
        txtFood = new javax.swing.JTextField();
        lblExpenditure = new javax.swing.JLabel();
        lblIncome = new javax.swing.JLabel();
        txtDonation = new javax.swing.JTextField();
        lblDonation = new javax.swing.JLabel();
        txtOther = new javax.swing.JTextField();
        lblOthers = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();

        panelControl.setBackground(new java.awt.Color(51, 51, 51));

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnBudget.setText("Budget");
        btnBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBudgetActionPerformed(evt);
            }
        });

        btnFund.setText("Public Fund");
        btnFund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFundActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelControlLayout = new javax.swing.GroupLayout(panelControl);
        panelControl.setLayout(panelControlLayout);
        panelControlLayout.setHorizontalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBudget, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFund, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelControlLayout.setVerticalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(btnHome)
                .addGap(59, 59, 59)
                .addComponent(btnBudget)
                .addGap(18, 18, 18)
                .addComponent(btnFund)
                .addContainerGap(478, Short.MAX_VALUE))
        );

        SplitPaneFundManager.setLeftComponent(panelControl);

        panelWork.setLayout(new java.awt.CardLayout());

        panelHome.setBackground(new java.awt.Color(255, 255, 255));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle2.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("NGO Fund Manager");
        panelHome.add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 639, -1));

        lblRole.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lblRole.setText("Role: Fund Manager");
        panelHome.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 110, 179, -1));

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        panelHome.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 130, -1, -1));

        panelWork.add(panelHome, "card2");

        panelPublicFund.setBackground(new java.awt.Color(255, 255, 255));
        panelPublicFund.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablePublicFund.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Message", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ScrollPane.setViewportView(tablePublicFund);

        panelPublicFund.add(ScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 610, 270));

        lblTitle3.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        lblTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle3.setText("Public Funds");
        panelPublicFund.add(lblTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 575, -1));

        panelWork.add(panelPublicFund, "card4");

        panelBudget.setBackground(new java.awt.Color(255, 255, 255));
        panelBudget.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle8.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        lblTitle8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle8.setText("Budget");
        panelBudget.add(lblTitle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 740, -1));

        lblTotal.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lblTotal.setText("Total ($):");
        panelBudget.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 135, -1, -1));
        panelBudget.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 139, 294, 29));

        lblEducation.setText("Education:");
        panelBudget.add(lblEducation, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 289, -1, -1));
        panelBudget.add(txtEducation, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 286, 166, -1));

        lblHealth.setText("Health:");
        panelBudget.add(lblHealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 329, -1, -1));
        panelBudget.add(txtHealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 326, 166, -1));

        lblFood.setText("Essential Items:");
        panelBudget.add(lblFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 369, -1, -1));
        panelBudget.add(txtFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 366, 166, -1));

        lblExpenditure.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblExpenditure.setText("Expenditure:");
        panelBudget.add(lblExpenditure, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 225, -1, -1));

        lblIncome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIncome.setText("Income:");
        panelBudget.add(lblIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 437, -1, -1));
        panelBudget.add(txtDonation, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 491, 166, -1));

        lblDonation.setText("Donations:");
        panelBudget.add(lblDonation, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 494, -1, -1));
        panelBudget.add(txtOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 531, 166, -1));

        lblOthers.setText("Others:");
        panelBudget.add(lblOthers, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 534, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        panelBudget.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, -1, -1));

        panelWork.add(panelBudget, "card9");

        SplitPaneFundManager.setRightComponent(panelWork);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneFundManager)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneFundManager)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initializeBud(){
        if(system.getBudgetList().getMoney()!=null){
            System.out.println("Hello");
            Integer donation = Integer.valueOf(system.getBudgetList().getMoney().getDonation());
            Integer other = Integer.valueOf(system.getBudgetList().getMoney().getOthers());
            Integer total = donation+other;
            Double edu = 0.3*total;
            Double hel = 0.3*total;
            Double ess = 0.4*total;
            txtDonation.setText(String.valueOf(system.getBudgetList().getMoney().getDonation()));
            txtOther.setText(String.valueOf(system.getBudgetList().getMoney().getOthers()));
            txtTotal.setText(String.valueOf(donation+other));
            txtEducation.setText(String.valueOf(edu));
            txtHealth.setText(String.valueOf(hel));
            txtFood.setText(String.valueOf(ess));
        }
        else{
            txtDonation.setText(String.valueOf(0));
            txtOther.setText(String.valueOf(0));
            txtTotal.setText(String.valueOf(0));
            txtEducation.setText(String.valueOf(0));
            txtHealth.setText(String.valueOf(0));
            txtFood.setText(String.valueOf(0));
        
        }
    }
    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        //        CardLayout cardLayout = (CardLayout) panelWork.getLayout();
        //        panelWork.add("NgoHome", panelHome);
        //        cardLayout.next(panelWork);
        panelWork.removeAll();
        panelWork.add(panelHome);
        panelWork.repaint();
        panelWork.revalidate();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBudgetActionPerformed
        // TODO add your handling code here:
        panelWork.removeAll();
        panelWork.add(panelBudget);
        panelWork.repaint();
        panelWork.revalidate();
    }//GEN-LAST:event_btnBudgetActionPerformed

    private void btnFundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFundActionPerformed
        // TODO add your handling code here:
        panelWork.removeAll();
        panelWork.add(panelPublicFund);
        panelWork.repaint();
        panelWork.revalidate();
    }//GEN-LAST:event_btnFundActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
        cardPanel.remove(this);
        cardLayout.previous(cardPanel);

    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if(system.getBudgetList()==null){
            Budget b = system.getBudgetList().addBudget();
            Integer donation = b.getDonation();
            Integer other = b.getOthers();
            Integer total = donation+other;

            b.setDonation(Integer.valueOf(txtDonation.getText()));
            b.setOthers(Integer.valueOf(txtOther.getText()));
            b.setTotal(total);

            Double edu = 0.3*total;
            Double hel = 0.3*total;
            Double ess = 0.4*total;

            txtEducation.setText(String.valueOf(edu));
            txtHealth.setText(String.valueOf(hel));
            txtFood.setText(String.valueOf(ess));

        }
        else{
            system.getBudgetList().getBudgetList().clear();
            Budget b = system.getBudgetList().addBudget();
            b.setDonation(Integer.valueOf(txtDonation.getText()));
            b.setOthers(Integer.valueOf(txtOther.getText()));

            Integer donation = b.getDonation();
            Integer other = b.getOthers();
            Integer total = donation+other;
            Double edu = 0.3*total;
            Double hel = 0.3*total;
            Double ess = 0.4*total;
            txtTotal.setText(String.valueOf(total));
            txtEducation.setText(String.valueOf(edu));
            txtHealth.setText(String.valueOf(hel));
            txtFood.setText(String.valueOf(ess));
        }
        JOptionPane.showMessageDialog(this, "Budget updated succefully");

    }//GEN-LAST:event_btnUpdateActionPerformed


    private void populatePublicFund(){
    
        DefaultTableModel model = (DefaultTableModel) tablePublicFund.getModel();
        model.setRowCount(0);
        
//        
            for(Donation man: system.getDonationList().getDonationList()){

                Object[] row = new Object[5];
                row[0] = man; 
                row[1] = man.getComment();
                row[2] = man.getAmt();
                model.addRow(row);
            }
            
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JSplitPane SplitPaneFundManager;
    private javax.swing.JButton btnBudget;
    private javax.swing.JButton btnFund;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblDonation;
    private javax.swing.JLabel lblEducation;
    private javax.swing.JLabel lblExpenditure;
    private javax.swing.JLabel lblFood;
    private javax.swing.JLabel lblHealth;
    private javax.swing.JLabel lblIncome;
    private javax.swing.JLabel lblOthers;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JLabel lblTitle8;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelBudget;
    private javax.swing.JPanel panelControl;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelPublicFund;
    private javax.swing.JPanel panelWork;
    private javax.swing.JTable tablePublicFund;
    private javax.swing.JTextField txtDonation;
    private javax.swing.JTextField txtEducation;
    private javax.swing.JTextField txtFood;
    private javax.swing.JTextField txtHealth;
    private javax.swing.JTextField txtOther;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
