/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.StudentActions;

import Business.Business;
import Business.UserAccount;
import Courses.Course;
import Professor.Professor;
import Student.Student;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SrushtiGhatage
 */
public class CourseListJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CourseListJPanel
     */
    public CourseListJPanel() {
        initComponents();
    }
    private Business business;
     private UserAccount useraccount;
     DefaultTableModel tableModel;
     Student s;
     Course c;
     
     public CourseListJPanel(Business business, UserAccount useraccount) {
        initComponents();
        this.business = business;
        this.useraccount = useraccount;
        this.tableModel= (DefaultTableModel) jTable1.getModel();
       
        s = this.business.getStudentDirectory().findStudentByUsername(this.useraccount.getUsername());
        populateTable();
        lblIsGradCompleted.setText(String.valueOf(s.isIsApprovedForGraduation()));
    }
     public void populateTable(){
         tableModel.setRowCount(0);
        
        for(Course c: s.getCoursesTaken())
                {
            
            Object[] row= new Object[4];
            
            row[0]= c.getCourseName();
            row[1]= c.getProfessorName();
            row[2]= c.getCourseNumberOfCredits();
            row[3]=c.getCourseTerm();
            
            tableModel.addRow(row);
        }
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        btnviewcourse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblcoursename = new javax.swing.JLabel();
        lblprofessorname = new javax.swing.JLabel();
        lblRindex = new javax.swing.JLabel();
        lblCcredit = new javax.swing.JLabel();
        lblCprice = new javax.swing.JLabel();
        lblCschedule = new javax.swing.JLabel();
        lblCterm = new javax.swing.JLabel();
        lblClocation = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblIsGradCompleted = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setBackground(new java.awt.Color(0, 204, 204));

        btnviewcourse.setBackground(new java.awt.Color(102, 102, 102));
        btnviewcourse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnviewcourse.setForeground(new java.awt.Color(255, 255, 255));
        btnviewcourse.setText("VIEW COURSE DETAILS");
        btnviewcourse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnviewcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewcourseActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course Name", "Professor Name", "Course Credit", "Course Term"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Course Name");

        jLabel3.setText("Professor Name");

        jLabel4.setText("Professor Reputation Index");

        jLabel5.setText("Course credit");

        jLabel6.setText("Course Price");

        jLabel7.setText("Course Schedule");

        jLabel8.setText("Course Term");

        jLabel9.setText("Course Location");

        lblcoursename.setText("jLabel10");

        lblprofessorname.setText("jLabel11");

        lblRindex.setText("jLabel12");

        lblCcredit.setText("jLabel13");

        lblCprice.setText("jLabel14");

        lblCschedule.setText("jLabel15");

        lblCterm.setText("jLabel16");

        lblClocation.setText("jLabel17");

        jLabel1.setText("Is Graduation Completed?");

        lblIsGradCompleted.setText("jLabel10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(btnviewcourse)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIsGradCompleted)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblprofessorname)
                        .addComponent(lblRindex)
                        .addComponent(lblCcredit)
                        .addComponent(lblCprice)
                        .addComponent(lblCschedule)
                        .addComponent(lblCterm)
                        .addComponent(lblClocation))
                    .addComponent(lblcoursename, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblIsGradCompleted))
                        .addGap(65, 65, 65)
                        .addComponent(btnviewcourse)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblcoursename))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblprofessorname))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblRindex))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblCcredit))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblCprice))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblCschedule))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblCterm))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblClocation))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnviewcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewcourseActionPerformed
        // TODO add your handling code here:
        int selectedRow= jTable1.getSelectedRow();
         String id = (String) jTable1.getValueAt(selectedRow,0);
         c = this.business.getCourseDirectory().findCourseByName(id);
        lblcoursename.setText(c.getCourseName());
        lblCcredit.setText(c.getCourseNumberOfCredits());
        lblCprice.setText(c.getCoursePrice());
        lblCterm.setText(c.getCourseTerm());
        lblprofessorname.setText(c.getProfessorName());
        Professor p = this.business.getProfessorDirectory().findProfessorByCourse(c);
        lblRindex.setText(String.valueOf(p.getReputationIndex()));
        lblCschedule.setText(c.getCourseSchedule());
        lblClocation.setText(c.getCourseLocation());
        
    }//GEN-LAST:event_btnviewcourseActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnviewcourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCcredit;
    private javax.swing.JLabel lblClocation;
    private javax.swing.JLabel lblCprice;
    private javax.swing.JLabel lblCschedule;
    private javax.swing.JLabel lblCterm;
    private javax.swing.JLabel lblIsGradCompleted;
    private javax.swing.JLabel lblRindex;
    private javax.swing.JLabel lblcoursename;
    private javax.swing.JLabel lblprofessorname;
    // End of variables declaration//GEN-END:variables
}
