/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.StudentActions;

import Business.Business;
import Business.UserAccount;
import Courses.Course;
import Professor.Professor;
import Student.Student;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @SrushtiGhatage
 */
public class SearchCoursesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchCoursesJPanel
     */
    private Business business;
     private UserAccount useraccount;
     DefaultTableModel tableModel;
     Student s;
     Course c;
    public SearchCoursesJPanel() {
        initComponents();
    }
     public SearchCoursesJPanel(Business business, UserAccount useraccount) {
        initComponents();
        this.business = business;
        this.useraccount = useraccount;
        this.tableModel= (DefaultTableModel) jTable2.getModel();
        populateDropdown();
        s = this.business.getStudentDirectory().findStudentByUsername(this.useraccount.getUsername());
    }
     
      public void populateDropdown(){
          cmbboxPname.removeAllItems();
        
        for(Professor p: this.business.getProfessorDirectory().getProfessorList()) {
            cmbboxPname.addItem(p.getUserName());
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbboxPname = new javax.swing.JComboBox<>();
        txtCname = new javax.swing.JTextField();
        txtClocation = new javax.swing.JTextField();
        txtCLang = new javax.swing.JTextField();
        btnSearchbyProf = new javax.swing.JButton();
        btnSearchbyCname = new javax.swing.JButton();
        btnSearchbyClocation = new javax.swing.JButton();
        btnSearchbyClang = new javax.swing.JButton();
        btnregister = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Course Name", "Professor Name", "Course Credit", "Course Term", "Course Price", "Course Location", "Course Language", "Professor Reputation Index"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("Search by Professor Name");

        jLabel2.setText("Serach by Course Name");

        jLabel3.setText("Search by Location");

        jLabel4.setText("Seach by Language");

        cmbboxPname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbboxPnameActionPerformed(evt);
            }
        });

        txtCname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnameActionPerformed(evt);
            }
        });

        btnSearchbyProf.setText("SEARCH");
        btnSearchbyProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchbyProfActionPerformed(evt);
            }
        });

        btnSearchbyCname.setText("SEARCH");
        btnSearchbyCname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchbyCnameActionPerformed(evt);
            }
        });

        btnSearchbyClocation.setText("SEARCH");
        btnSearchbyClocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchbyClocationActionPerformed(evt);
            }
        });

        btnSearchbyClang.setText("SEARCH");
        btnSearchbyClang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchbyClangActionPerformed(evt);
            }
        });

        btnregister.setText("REGISTER");
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCname)
                            .addComponent(txtClocation)
                            .addComponent(txtCLang)
                            .addComponent(cmbboxPname, 0, 94, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearchbyProf)
                            .addComponent(btnSearchbyCname)
                            .addComponent(btnSearchbyClocation)
                            .addComponent(btnSearchbyClang))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnregister, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbboxPname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchbyProf))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchbyCname))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtClocation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchbyClocation))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCLang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchbyClang))
                .addGap(36, 36, 36)
                .addComponent(btnregister, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbboxPnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbboxPnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbboxPnameActionPerformed

    private void txtCnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnameActionPerformed

    private void btnSearchbyProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchbyProfActionPerformed
        // TODO add your handling code here:
         tableModel.setRowCount(0);
        Professor p = this.business.getProfessorDirectory().findProfessorByUsername(cmbboxPname.getSelectedItem().toString());
        for(Course c : p.getProfessorCourses())
                {
            
            Object[] row= new Object[8];
            
            row[0]= c.getCourseName();
            row[1]= c.getProfessorName();
            row[2]= c.getCourseNumberOfCredits();
            row[3]=c.getCourseTerm();
            row[4]=c.getCoursePrice();
            row[5]=c.getCourseLocation();
            row[6]=c.getCourseLanguage();
            row[7]=c.getReputationIndex();
            tableModel.addRow(row);
        }
    }//GEN-LAST:event_btnSearchbyProfActionPerformed

    private void btnSearchbyCnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchbyCnameActionPerformed
        // TODO add your handling code here:
          tableModel.setRowCount(0);
        
        for(Course c : this.business.getCourseDirectory().getCourseList())
                {
                    if(c.getCourseName().equalsIgnoreCase(txtCname.getText())){
                         Object[] row= new Object[8];
            
            row[0]= c.getCourseName();
            row[1]= c.getProfessorName();
            row[2]= c.getCourseNumberOfCredits();
            row[3]=c.getCourseTerm();
            row[4]=c.getCoursePrice();
            row[5]=c.getCourseLocation();
            row[6]=c.getCourseLanguage();
            row[7]=c.getReputationIndex();
            
            tableModel.addRow(row);
                    }
            
           
        }
    }//GEN-LAST:event_btnSearchbyCnameActionPerformed

    private void btnSearchbyClocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchbyClocationActionPerformed
        // TODO add your handling code here:
        tableModel.setRowCount(0);
        
        for(Course c : this.business.getCourseDirectory().getCourseList())
                {
                    if(c.getCourseLocation().equalsIgnoreCase(txtClocation.getText())){
                         Object[] row= new Object[8];
            
            row[0]= c.getCourseName();
            row[1]= c.getProfessorName();
            row[2]= c.getCourseNumberOfCredits();
            row[3]=c.getCourseTerm();
            row[4]=c.getCoursePrice();
            row[5]=c.getCourseLocation();
            row[6]=c.getCourseLanguage();
            row[7]=c.getReputationIndex();
            
            tableModel.addRow(row);
                    }
            
           
        }
    }//GEN-LAST:event_btnSearchbyClocationActionPerformed

    private void btnSearchbyClangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchbyClangActionPerformed
        // TODO add your handling code here:
        tableModel.setRowCount(0);
        
        for(Course c : this.business.getCourseDirectory().getCourseList())
                {
                    if(c.getCourseLanguage().equalsIgnoreCase(txtCLang.getText())){
                         Object[] row= new Object[8];
            
            row[0]= c.getCourseName();
            row[1]= c.getProfessorName();
            row[2]= c.getCourseNumberOfCredits();
            row[3]=c.getCourseTerm();
            row[4]=c.getCoursePrice();
            row[5]=c.getCourseLocation();
            row[6]=c.getCourseLanguage();
            row[7]=c.getReputationIndex();
            
            
            tableModel.addRow(row);
                    }
            
           
        }
    }//GEN-LAST:event_btnSearchbyClangActionPerformed

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        // TODO add your handling code here:
        int selectedRow= jTable2.getSelectedRow();
         String id = (String) jTable2.getValueAt(selectedRow,0);
         c = this.business.getCourseDirectory().findCourseByName(id);
         if(s.getCoursesTaken().size()>7){
            JOptionPane.showMessageDialog(null, "Cannot register more than 8 courses");
        }
        else{
       s.getCoursesTaken().add(c);
       JOptionPane.showMessageDialog(null, "Course registration is successfull");
         }
    }//GEN-LAST:event_btnregisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchbyClang;
    private javax.swing.JButton btnSearchbyClocation;
    private javax.swing.JButton btnSearchbyCname;
    private javax.swing.JButton btnSearchbyProf;
    private javax.swing.JButton btnregister;
    private javax.swing.JComboBox<String> cmbboxPname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtCLang;
    private javax.swing.JTextField txtClocation;
    private javax.swing.JTextField txtCname;
    // End of variables declaration//GEN-END:variables
}
