/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui.School;

import JobApp.Applicant.TeacherApply;
import Ngo.Budget.Budget;
import School.Application.Application;
import School.Principal.Principal;
import School.Student.Student;
import School.Teacher.Teacher;
import System.Directories.DB4OUtil;
import System.Directories.DataValidation;
import System.Directories.MainSystem;
import java.awt.CardLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author megha
 */
public class PrincipalWorkspace extends javax.swing.JPanel {

    /**
     * Creates new form PrincipalWorkspace
     */
    private JPanel cardPanel;
    private Principal principal;
    private MainSystem system;
    private DB4OUtil dB4OUtil;
    private final String FILENAME = "ProjectDataBank.db4o";
    private DataValidation data;
    
    public PrincipalWorkspace(Principal principal,JPanel cardPanel, MainSystem system, DB4OUtil dB4OUtil) {
        initComponents();
        this.principal = principal;
        this.cardPanel = cardPanel;
        this.system = system;
        this.dB4OUtil = dB4OUtil;
        this.data = new DataValidation();
        
        populateTeacherTable();
  
        populateAppTable();
        populateApplicationTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPanePrincipal = new javax.swing.JSplitPane();
        panelControl = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnTeacher = new javax.swing.JButton();
        btnApplication = new javax.swing.JButton();
        btnJobApp = new javax.swing.JButton();
        panelWork = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        lblTitle2 = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelMarks = new javax.swing.JPanel();
        panelApplications = new javax.swing.JPanel();
        ScrollPane6 = new javax.swing.JScrollPane();
        tableApplication = new javax.swing.JTable();
        lblApplicationNo = new javax.swing.JLabel();
        txtApplicationNo = new javax.swing.JTextField();
        lblChildName = new javax.swing.JLabel();
        txtChildName = new javax.swing.JTextField();
        lblChildAge = new javax.swing.JLabel();
        txtChildAge = new javax.swing.JTextField();
        lblChildName2 = new javax.swing.JLabel();
        txtChildDOB = new javax.swing.JTextField();
        lblChildName3 = new javax.swing.JLabel();
        cmbChildGender = new javax.swing.JComboBox<>();
        lblChildName4 = new javax.swing.JLabel();
        txtChildSchool = new javax.swing.JTextField();
        lblChildName5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtChildComment = new javax.swing.JTextArea();
        lblStatus = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        btnReject = new javax.swing.JButton();
        lblTitle7 = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        lblChildName6 = new javax.swing.JLabel();
        txtChildClass = new javax.swing.JTextField();
        lblChildName7 = new javax.swing.JLabel();
        txtNgo = new javax.swing.JComboBox<>();
        btnAccept = new javax.swing.JButton();
        panelJobApply = new javax.swing.JPanel();
        lblTitle5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableJobApp = new javax.swing.JTable();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblUsername1 = new javax.swing.JLabel();
        txtAppId = new javax.swing.JTextField();
        lblUsername2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtQua = new javax.swing.JTextField();
        lblQua = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblAge1 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lblQua1 = new javax.swing.JLabel();
        txtEx = new javax.swing.JTextField();
        lblQua2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtComm = new javax.swing.JTextArea();
        lblSub = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        lblSchool = new javax.swing.JLabel();
        txtSchool = new javax.swing.JTextField();
        lblStatus1 = new javax.swing.JLabel();
        txtStatus1 = new javax.swing.JTextField();
        lblEmailid = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        btnAccept1 = new javax.swing.JButton();
        btnReject1 = new javax.swing.JButton();
        btnView1 = new javax.swing.JButton();
        panelTeacher = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        lblTeacherName = new javax.swing.JLabel();
        lblTeacherAge = new javax.swing.JLabel();
        txtTeacherName = new javax.swing.JTextField();
        txtTeacherAge = new javax.swing.JTextField();
        btnTeacherView = new javax.swing.JButton();
        ScrollPaneNgoManager = new javax.swing.JScrollPane();
        tableTeacher = new javax.swing.JTable();
        btnTeacherDelete = new javax.swing.JButton();
        lblTeacherDOB = new javax.swing.JLabel();
        txtTeacherDOB = new javax.swing.JTextField();
        lblTeacherUsername = new javax.swing.JLabel();
        txtTeacherUsername = new javax.swing.JTextField();
        lblTeacherEmailId = new javax.swing.JLabel();
        txtTeacherEmailId = new javax.swing.JTextField();
        txtTeacherPhno = new javax.swing.JTextField();
        lblTeacherPhno = new javax.swing.JLabel();
        lblTeacherPassword = new javax.swing.JLabel();
        txtTeacherPassword = new javax.swing.JPasswordField();
        lblNgoManagerId = new javax.swing.JLabel();
        txtTeacherId = new javax.swing.JTextField();
        lblTeacherSearch = new javax.swing.JLabel();
        txtTeacherSearch = new javax.swing.JTextField();
        lblTeacherGender = new javax.swing.JLabel();
        cmbTeacherGender = new javax.swing.JComboBox<>();
        lblTeacherRole = new javax.swing.JLabel();
        txtTeacherRole = new javax.swing.JTextField();
        lblTeacherEx = new javax.swing.JLabel();
        txtTeacherEx = new javax.swing.JTextField();
        btnTeacherCreate = new javax.swing.JButton();
        btnTeacherUpdate = new javax.swing.JButton();

        panelControl.setBackground(new java.awt.Color(51, 51, 51));

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnTeacher.setText("Teacher");
        btnTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherActionPerformed(evt);
            }
        });

        btnApplication.setText("Applications");
        btnApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplicationActionPerformed(evt);
            }
        });

        btnJobApp.setText("Job Applications");
        btnJobApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJobAppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelControlLayout = new javax.swing.GroupLayout(panelControl);
        panelControl.setLayout(panelControlLayout);
        panelControlLayout.setHorizontalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTeacher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelControlLayout.createSequentialGroup()
                        .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnApplication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnJobApp))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelControlLayout.setVerticalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btnHome)
                .addGap(28, 28, 28)
                .addComponent(btnApplication)
                .addGap(18, 18, 18)
                .addComponent(btnJobApp)
                .addGap(134, 134, 134)
                .addComponent(btnTeacher)
                .addContainerGap(381, Short.MAX_VALUE))
        );

        SplitPanePrincipal.setLeftComponent(panelControl);

        panelWork.setLayout(new java.awt.CardLayout());

        panelHome.setBackground(new java.awt.Color(255, 255, 255));
        panelHome.setLayout(null);

        lblTitle2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("School");
        panelHome.add(lblTitle2);
        lblTitle2.setBounds(0, 6, 1300, 32);

        lblRole.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblRole.setText("Role: Principal");
        panelHome.add(lblRole);
        lblRole.setBounds(1091, 95, 139, 16);

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        panelHome.add(btnLogOut);
        btnLogOut.setBounds(1091, 117, 73, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/principal workspace.gif"))); // NOI18N
        panelHome.add(jLabel1);
        jLabel1.setBounds(310, 100, 1010, 500);

        panelWork.add(panelHome, "card2");

        javax.swing.GroupLayout panelMarksLayout = new javax.swing.GroupLayout(panelMarks);
        panelMarks.setLayout(panelMarksLayout);
        panelMarksLayout.setHorizontalGroup(
            panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1166, Short.MAX_VALUE)
        );
        panelMarksLayout.setVerticalGroup(
            panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        panelWork.add(panelMarks, "card4");

        panelApplications.setBackground(new java.awt.Color(255, 255, 255));

        tableApplication.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Application Id", "Name", "Age", "Gender", "NGO", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ScrollPane6.setViewportView(tableApplication);

        lblApplicationNo.setText("Application No:");

        lblChildName.setText("Name:");

        lblChildAge.setText("Age:");

        lblChildName2.setText("DOB:");

        lblChildName3.setText("Gender:");

        cmbChildGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));

        lblChildName4.setText("School:");

        txtChildSchool.setEditable(false);
        txtChildSchool.setText("School");

        lblChildName5.setText("Comment:");

        txtChildComment.setColumns(20);
        txtChildComment.setRows(5);
        jScrollPane1.setViewportView(txtChildComment);

        lblStatus.setText("Status:");

        txtStatus.setEditable(false);
        txtStatus.setText("Pending");

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        lblTitle7.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        lblTitle7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle7.setText("Applications");

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lblChildName6.setText("Class:");

        lblChildName7.setText("NGO:");

        txtNgo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelApplicationsLayout = new javax.swing.GroupLayout(panelApplications);
        panelApplications.setLayout(panelApplicationsLayout);
        panelApplicationsLayout.setHorizontalGroup(
            panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelApplicationsLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelApplicationsLayout.createSequentialGroup()
                        .addGroup(panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblChildName2)
                            .addGroup(panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(panelApplicationsLayout.createSequentialGroup()
                                    .addComponent(lblChildName3)
                                    .addGap(59, 59, 59)
                                    .addComponent(cmbChildGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(txtChildDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelApplicationsLayout.createSequentialGroup()
                                    .addComponent(lblChildAge)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtChildAge, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelApplicationsLayout.createSequentialGroup()
                                        .addComponent(lblChildName)
                                        .addGap(66, 66, 66)
                                        .addComponent(txtChildName, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelApplicationsLayout.createSequentialGroup()
                                        .addComponent(lblApplicationNo)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtApplicationNo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelApplicationsLayout.createSequentialGroup()
                                .addComponent(lblChildName6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtChildClass, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelApplicationsLayout.createSequentialGroup()
                                .addComponent(lblStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelApplicationsLayout.createSequentialGroup()
                                .addGroup(panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelApplicationsLayout.createSequentialGroup()
                                        .addGroup(panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblChildName4)
                                            .addComponent(lblChildName5))
                                        .addGap(27, 27, 27))
                                    .addGroup(panelApplicationsLayout.createSequentialGroup()
                                        .addComponent(lblChildName7)
                                        .addGap(53, 53, 53)))
                                .addGroup(panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtChildSchool)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(txtNgo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnView)
                        .addComponent(ScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelApplicationsLayout.createSequentialGroup()
                        .addComponent(btnAccept)
                        .addGap(18, 18, 18)
                        .addComponent(btnReject)
                        .addGap(286, 286, 286)))
                .addContainerGap(491, Short.MAX_VALUE))
        );
        panelApplicationsLayout.setVerticalGroup(
            panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelApplicationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle7)
                .addGap(54, 54, 54)
                .addComponent(ScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelApplicationsLayout.createSequentialGroup()
                        .addGroup(panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApplicationNo)
                            .addComponent(txtApplicationNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChildName)
                            .addComponent(txtChildName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChildAge)
                            .addComponent(txtChildAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChildName2)
                            .addComponent(txtChildDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelApplicationsLayout.createSequentialGroup()
                        .addGroup(panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChildName6)
                            .addComponent(txtChildClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStatus))
                        .addGap(18, 18, 18)
                        .addGroup(panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChildName4)
                            .addComponent(txtChildSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChildName7)
                            .addComponent(txtNgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblChildName3)
                        .addComponent(cmbChildGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblChildName5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelApplicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReject)
                    .addComponent(btnAccept))
                .addGap(32, 32, 32))
        );

        panelWork.add(panelApplications, "card6");

        panelJobApply.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle5.setText("Job Application");

        tableJobApp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Applicant Id", "Name", "Subject", "Email-Id", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableJobApp);

        lblUsername.setText("Username:");

        txtUsername.setEditable(false);

        lblUsername1.setText("Application Id:");

        txtAppId.setEditable(false);

        lblUsername2.setText("Name:");

        txtName.setEditable(false);

        txtQua.setEditable(false);

        lblQua.setText("Qualification:");

        lblAge.setText("Age:");

        txtAge.setEditable(false);

        lblAge1.setText("Gender:");

        txtGender.setEditable(false);

        lblQua1.setText("Experience:");

        txtEx.setEditable(false);

        lblQua2.setText("Comment:");

        txtComm.setColumns(20);
        txtComm.setRows(5);
        jScrollPane3.setViewportView(txtComm);

        lblSub.setText("Subject:");

        txtSubject.setEditable(false);

        lblSchool.setText("School:");

        txtSchool.setEditable(false);
        txtSchool.setText("School");

        lblStatus1.setText("Status:");

        txtStatus1.setEditable(false);
        txtStatus1.setText("Pending");

        lblEmailid.setText("Email-Id:");

        txtEmailId.setEditable(false);

        btnAccept1.setText("Accept");
        btnAccept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccept1ActionPerformed(evt);
            }
        });

        btnReject1.setText("Reject");
        btnReject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReject1ActionPerformed(evt);
            }
        });

        btnView1.setText("View");
        btnView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelJobApplyLayout = new javax.swing.GroupLayout(panelJobApply);
        panelJobApply.setLayout(panelJobApplyLayout);
        panelJobApplyLayout.setHorizontalGroup(
            panelJobApplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle5, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
            .addGroup(panelJobApplyLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelJobApplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelJobApplyLayout.createSequentialGroup()
                        .addComponent(btnView1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(panelJobApplyLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelJobApplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername1)
                    .addComponent(lblUsername)
                    .addComponent(lblUsername2)
                    .addComponent(lblQua)
                    .addComponent(lblAge)
                    .addComponent(lblAge1)
                    .addComponent(lblQua1))
                .addGap(27, 27, 27)
                .addGroup(panelJobApplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEx)
                    .addComponent(txtGender)
                    .addComponent(txtAge)
                    .addComponent(txtQua)
                    .addComponent(txtName)
                    .addComponent(txtUsername)
                    .addComponent(txtAppId, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelJobApplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelJobApplyLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(panelJobApplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSchool)
                            .addComponent(lblStatus1)
                            .addComponent(lblSub)
                            .addComponent(lblEmailid)
                            .addComponent(lblQua2))
                        .addGap(46, 46, 46)
                        .addGroup(panelJobApplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmailId)
                            .addComponent(txtStatus1)
                            .addComponent(txtSchool)
                            .addComponent(txtSubject)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelJobApplyLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(btnAccept1)
                        .addGap(34, 34, 34)
                        .addComponent(btnReject1)))
                .addContainerGap(559, Short.MAX_VALUE))
        );
        panelJobApplyLayout.setVerticalGroup(
            panelJobApplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJobApplyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle5)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnView1)
                .addGap(35, 35, 35)
                .addGroup(panelJobApplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelJobApplyLayout.createSequentialGroup()
                        .addGroup(panelJobApplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelJobApplyLayout.createSequentialGroup()
                                .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelJobApplyLayout.createSequentialGroup()
                                .addComponent(lblEmailid)
                                .addGap(18, 18, 18)
                                .addComponent(lblSub)
                                .addGap(18, 18, 18)
                                .addComponent(lblSchool)
                                .addGap(18, 18, 18)
                                .addComponent(lblStatus1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblQua2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAge1))
                    .addGroup(panelJobApplyLayout.createSequentialGroup()
                        .addGroup(panelJobApplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsername1)
                            .addComponent(txtAppId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelJobApplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsername)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelJobApplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsername2)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelJobApplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQua)
                            .addComponent(txtQua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelJobApplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(panelJobApplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelJobApplyLayout.createSequentialGroup()
                        .addGroup(panelJobApplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQua1)
                            .addComponent(txtEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJobApplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAccept1)
                        .addComponent(btnReject1)))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        panelWork.add(panelJobApply, "card3");

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("Teacher");

        lblTeacherName.setText("Name:");

        lblTeacherAge.setText("Age:");

        btnTeacherView.setText("View");
        btnTeacherView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherViewActionPerformed(evt);
            }
        });

        tableTeacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Username", "Age", "Email-Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableTeacher.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ScrollPaneNgoManager.setViewportView(tableTeacher);

        btnTeacherDelete.setText("Delete");
        btnTeacherDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherDeleteActionPerformed(evt);
            }
        });

        lblTeacherDOB.setText("DOB:");

        lblTeacherUsername.setText("Username:");

        lblTeacherEmailId.setText("Email-Id:");

        lblTeacherPhno.setText("Phone No:");

        lblTeacherPassword.setText("Password:");

        lblNgoManagerId.setText("Teacher Id:");

        lblTeacherSearch.setText("Search:");

        lblTeacherGender.setText("Gender:");

        cmbTeacherGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));

        lblTeacherRole.setText("Role:");

        txtTeacherRole.setEditable(false);
        txtTeacherRole.setText("Teacher");

        lblTeacherEx.setText("Experience:");

        btnTeacherCreate.setText("Create");
        btnTeacherCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherCreateActionPerformed(evt);
            }
        });

        btnTeacherUpdate.setText("Update");
        btnTeacherUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTeacherLayout = new javax.swing.GroupLayout(panelTeacher);
        panelTeacher.setLayout(panelTeacherLayout);
        panelTeacherLayout.setHorizontalGroup(
            panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTeacherLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelTeacherLayout.createSequentialGroup()
                            .addComponent(lblTeacherSearch)
                            .addGap(18, 18, 18)
                            .addComponent(txtTeacherSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTeacherLayout.createSequentialGroup()
                                .addComponent(btnTeacherView)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTeacherDelete))
                            .addComponent(ScrollPaneNgoManager, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelTeacherLayout.createSequentialGroup()
                        .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNgoManagerId, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelTeacherLayout.createSequentialGroup()
                                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTeacherName)
                                    .addComponent(lblTeacherAge)
                                    .addComponent(lblTeacherDOB)
                                    .addComponent(lblTeacherUsername)
                                    .addComponent(lblTeacherRole))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGap(44, 44, 44)
                        .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTeacherRole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTeacherId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTeacherAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTeacherUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTeacherDOB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtTeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(114, 114, 114)
                        .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTeacherLayout.createSequentialGroup()
                                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTeacherEmailId)
                                    .addComponent(lblTeacherGender))
                                .addGap(42, 42, 42))
                            .addGroup(panelTeacherLayout.createSequentialGroup()
                                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTeacherPhno)
                                    .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTeacherEx)
                                        .addComponent(lblTeacherPassword)))
                                .addGap(30, 30, 30)))
                        .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelTeacherLayout.createSequentialGroup()
                                    .addComponent(btnTeacherCreate)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnTeacherUpdate))
                                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTeacherPassword)
                                    .addComponent(txtTeacherPhno, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbTeacherGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTeacherEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTeacherEx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(477, Short.MAX_VALUE))
        );
        panelTeacherLayout.setVerticalGroup(
            panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTeacherLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblTitle1)
                .addGap(64, 64, 64)
                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeacherSearch)
                    .addComponent(txtTeacherSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPaneNgoManager, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTeacherView)
                    .addComponent(btnTeacherDelete))
                .addGap(63, 63, 63)
                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTeacherLayout.createSequentialGroup()
                        .addComponent(txtTeacherId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTeacherUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTeacherUsername))
                        .addGap(20, 20, 20)
                        .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTeacherAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTeacherAge))
                        .addGap(28, 28, 28)
                        .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTeacherDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTeacherDOB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTeacherRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTeacherRole)))
                    .addGroup(panelTeacherLayout.createSequentialGroup()
                        .addComponent(lblNgoManagerId)
                        .addGap(18, 18, 18)
                        .addComponent(lblTeacherName))
                    .addGroup(panelTeacherLayout.createSequentialGroup()
                        .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTeacherLayout.createSequentialGroup()
                                .addComponent(cmbTeacherGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTeacherEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTeacherPhno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTeacherPhno))
                                .addGap(18, 18, 18)
                                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTeacherEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTeacherEx))
                                .addGap(18, 18, 18)
                                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTeacherPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTeacherPassword)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTeacherLayout.createSequentialGroup()
                                .addComponent(lblTeacherGender)
                                .addGap(18, 18, 18)
                                .addComponent(lblTeacherEmailId)
                                .addGap(124, 124, 124)))
                        .addGap(40, 40, 40)
                        .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTeacherCreate)
                            .addComponent(btnTeacherUpdate))))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        panelWork.add(panelTeacher, "card2");

        SplitPanePrincipal.setRightComponent(panelWork);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanePrincipal)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        panelWork.removeAll();
        panelWork.add(panelHome);
        panelWork.repaint();
        panelWork.revalidate();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherActionPerformed
        // TODO add your handling code here:
        panelWork.removeAll();
        panelWork.add(panelTeacher);
        panelWork.repaint();
        panelWork.revalidate();
    }//GEN-LAST:event_btnTeacherActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        dB4OUtil.storeSystem(system);
        CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
        cardPanel.remove(this);
        cardLayout.previous(cardPanel);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplicationActionPerformed
        // TODO add your handling code here:
        panelWork.removeAll();
        panelWork.add(panelApplications);
        panelWork.repaint();
        panelWork.revalidate();
    }//GEN-LAST:event_btnApplicationActionPerformed

    private void btnJobAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJobAppActionPerformed
        // TODO add your handling code here:
        panelWork.removeAll();
        panelWork.add(panelJobApply);
        panelWork.repaint();
        panelWork.revalidate();
    }//GEN-LAST:event_btnJobAppActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        Integer selectedRowIndex = tableApplication.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }
        else if(system.getApplicationList().getApplicationList().get(selectedRowIndex).getStatus().equals("Accepted")){

            JOptionPane.showMessageDialog(this, "The application is Accepted and cannot be Rejected");
            return;
        }
        else{
            //            System.out.println(a.getStatus());
            DefaultTableModel model = (DefaultTableModel) tableApplication.getModel();
            Application selApp = (Application) model.getValueAt(selectedRowIndex,0);

            selApp.setStatus("Rejected");

            populateApplicationTable();
        }
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        Integer selectedRowIndex = tableApplication.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        Application a = system.getApplicationList().getApplicationList().get(selectedRowIndex);
        if(a.getStatus().equals("Rejected") || a.getStatus().equals("Accepted") ){
            JOptionPane.showMessageDialog(this, "Only Pending status applications can be viewed");
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableApplication.getModel();
            Application selApp = (Application) model.getValueAt(selectedRowIndex,0);

            txtApplicationNo.setText(selApp.getAppNo());
            txtChildName.setText(selApp.getName());
            txtChildAge.setText(String.valueOf(selApp.getAge()));
            txtChildDOB.setText(selApp.getDob());
            cmbChildGender.setSelectedItem(selApp.getGender());
            txtChildClass.setText(selApp.getCls());
            txtStatus.setText(selApp.getStatus());
            txtNgo.setSelectedItem(selApp.getNgo());
            txtChildComment.setText(selApp.getComment());
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnAccept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccept1ActionPerformed
        // TODO add your handling code here:
        Integer selectedRowIndex = tableJobApp.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }
        else if(system.getApplist().getAppList().get(selectedRowIndex).getStatus().equals("Rejected")){
            JOptionPane.showMessageDialog(this, "The application is Rejected and cannot be Accepted");
            return;
        }
        else{
            DefaultTableModel model = (DefaultTableModel) tableJobApp.getModel();
            TeacherApply selApp = (TeacherApply) model.getValueAt(selectedRowIndex,0);
            selApp.setStatus("Accepted");

            populateAppTable();
        }

    }//GEN-LAST:event_btnAccept1ActionPerformed

    private void btnReject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReject1ActionPerformed
        // TODO add your handling code here:
        Integer selectedRowIndex = tableJobApp.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }
        else if(system.getApplist().getAppList().get(selectedRowIndex).getStatus().equals("Accepted")){
            JOptionPane.showMessageDialog(this, "The application is Rejected and cannot be Accepted");
            return;
        }
        else{
            DefaultTableModel model = (DefaultTableModel) tableJobApp.getModel();
            TeacherApply selApp = (TeacherApply) model.getValueAt(selectedRowIndex,0);
            selApp.setStatus("Rejected");

            populateAppTable();
        }
    }//GEN-LAST:event_btnReject1ActionPerformed

    private void btnView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView1ActionPerformed
        // TODO add your handling code here:
        Integer selectedRowIndex = tableJobApp.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        TeacherApply a = system.getApplist().getAppList().get(selectedRowIndex);
        if(a.getStatus().equals("Rejected") || a.getStatus().equals("Accepted") ){
            JOptionPane.showMessageDialog(this, "Only Pending status applications can be viewed");
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableJobApp.getModel();
            TeacherApply selApp = (TeacherApply) model.getValueAt(selectedRowIndex,0);

            txtAppId.setText(selApp.getAppId());
            txtUsername.setText(selApp.getUsername());
            txtName.setText(selApp.getName());
            txtAge.setText(String.valueOf(selApp.getAge()));
            txtGender.setText(selApp.getGender());
            txtEx.setText(String.valueOf(selApp.getExperience()));
            txtQua.setText(selApp.getQualification());
            txtComm.setText(selApp.getComment());
            txtSubject.setText(selApp.getSubject());
            txtEmailId.setText(selApp.getEmailId());
        }

    }//GEN-LAST:event_btnView1ActionPerformed

    private void btnTeacherViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherViewActionPerformed
        // TODO add your handling code here:
        Integer selectedRowIndex = tableTeacher.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableTeacher.getModel();
            Teacher selMan = (Teacher) model.getValueAt(selectedRowIndex,0);

            txtTeacherId.setText(selMan.getTeacherId());
            txtTeacherName.setText(selMan.getName());
            txtTeacherUsername.setText(selMan.getUsername());
            txtTeacherAge.setText(String.valueOf(selMan.getAge()));
            txtTeacherDOB.setText(selMan.getDob());
            cmbTeacherGender.setSelectedItem(selMan.getGender());
            txtTeacherRole.setText(selMan.getRole());
            txtTeacherEmailId.setText(selMan.getEmailId());
            txtTeacherPhno.setText(String.valueOf(selMan.getPhno()));
            txtTeacherEx.setText(String.valueOf(selMan.getExperience()));
            txtTeacherPassword.setText(selMan.getPassword());

        }
    }//GEN-LAST:event_btnTeacherViewActionPerformed

    private void btnTeacherDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherDeleteActionPerformed
        // TODO add your handling code here:
        Integer selectedRowIndex = tableTeacher.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableTeacher.getModel();
            Teacher selectedMan = (Teacher) model.getValueAt(selectedRowIndex,0);

            system.getTeacherList().deleteTeacher(selectedMan);

            JOptionPane.showMessageDialog(this, "Teacher deleted successfully.");

            //            dB4OUtil.storeSystem(system);
            populateTeacherTable();
        }
    }//GEN-LAST:event_btnTeacherDeleteActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        try{
            Integer selectedRowIndex = tableApplication.getSelectedRow();
            Integer ngofund = system.getBudgetList().getTotal();
            //        Integer amt = ngofund.getTotal();
            if (selectedRowIndex<0){

                JOptionPane.showMessageDialog(this, "Please select a row to view.");
                return;
            }
            else if(system.getApplicationList().getApplicationList().get(selectedRowIndex).getStatus().equals("Rejected")){
                JOptionPane.showMessageDialog(this, "The application is Rejected and cannot be Accepted");
                return;
            }
            else if(ngofund<20){
                JOptionPane.showMessageDialog(this, "Cannot accept as Ngo does not have sufficient funds");
                return;
            }
            else
            {

                DefaultTableModel model = (DefaultTableModel) tableApplication.getModel();
                Application selApp = (Application) model.getValueAt(selectedRowIndex,0);
                selApp.setStatus("Accepted");
                system.getBudgetList().getMoney().setTotal(ngofund - 20);

                Integer total = system.getBudgetList().getMoney().getTotal();
                Integer others = system.getBudgetList().getMoney().getOthers();
                Integer don = system.getBudgetList().getMoney().getDonation();

                if(others>=20){
                    system.getBudgetList().getMoney().setOthers(others - 20);
                }
                else{
                    system.getBudgetList().getMoney().setDonation(don-20);
                }

                populateApplicationTable();
            }
        }catch(NullPointerException ne){
            JOptionPane.showMessageDialog(this, "Cannot accept as Ngo does not have sufficient funds");
        }
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnTeacherCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherCreateActionPerformed
        // TODO add your handling code here:

        String id = txtTeacherId.getText();
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter the Id");
            return;
        }
        else if(system.getTeacherList().uiqueTeacherId(id)== false){
            JOptionPane.showMessageDialog(this, "Id already exist");
            return;
        }

        String name = txtTeacherName.getText();
        if(name.isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter the name");
            return;
        }

        String username = txtTeacherUsername.getText();
        if(username.isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter the username");
            return;
        }
        else if(system.getTeacherList().uniqueTeacherUsername(username)==false){
            JOptionPane.showMessageDialog(this, "Username already exist");
            return;
        }

        if(data.numcheck(txtTeacherAge.getText())==false){
            JOptionPane.showMessageDialog(this, "Enter valid age");
            return;
        }
        Integer age = Integer.valueOf(txtTeacherAge.getText());

        String dob = txtTeacherDOB.getText();
        if(!data.dateCheck(dob)){
            JOptionPane.showMessageDialog(this, "Please enter correct date in format mm/dd/yyyy");
            return;
        }

        String gender = String.valueOf(cmbTeacherGender.getSelectedItem());

        String role = txtTeacherRole.getText();

        String emailid= txtTeacherEmailId.getText();
        if(!data.emailCheck(emailid)){
            JOptionPane.showMessageDialog(this, "Enter valid email id");
            return;
        }

        if(!data.phnocheck(txtTeacherPhno.getText())){
            JOptionPane.showMessageDialog(this, "Enter valid phone no");
            return;
        }
        Long phno = Long.valueOf(txtTeacherPhno.getText());

        if(data.numcheck(txtTeacherEx.getText())==false){
            JOptionPane.showMessageDialog(this, "Enter valid Experience");
            return;
        }
        Integer experience = Integer.valueOf(txtTeacherEx.getText());

        String pass = txtTeacherPassword.getText();
        if(pass.isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter valid password");
            return;
        }

        Teacher newTeacher = system.getTeacherList().addTeacher();

        newTeacher.setTeacherId(id);
        newTeacher.setName(name);
        newTeacher.setUsername(username);
        newTeacher.setAge(age);
        newTeacher.setDob(dob);
        newTeacher.setGender(gender);
        newTeacher.setRole(role);
        newTeacher.setEmailId(emailid);
        newTeacher.setPhno(phno);
        newTeacher.setExperience(experience);
        newTeacher.setPassword(pass);

        JOptionPane.showMessageDialog(this, "Teacher created successfully");

        txtTeacherId.setText("");
        txtTeacherName.setText("");
        txtTeacherUsername.setText("");
        txtTeacherAge.setText("");
        txtTeacherDOB.setText("");
        txtTeacherEmailId.setText("");
        txtTeacherPhno.setText("");
        txtTeacherEx.setText("");
        txtTeacherPassword.setText("");

        //        dB4OUtil.storeSystem(system);
        populateTeacherTable();
//        populateCombo();
    }//GEN-LAST:event_btnTeacherCreateActionPerformed

    private void btnTeacherUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherUpdateActionPerformed
        // TODO add your handling code here:
        Integer selectedRowIndex = tableTeacher.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableTeacher.getModel();
            Teacher selMan = (Teacher) model.getValueAt(selectedRowIndex,0);

            //            selMan.setTeacherId(txtTeacherId.getText());

            selMan.setName(txtTeacherName.getText());
            if(txtTeacherName.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Enter valid name");
                return;
            }

            //            selMan.setUsername(txtTeacherUsername.getText());

            if(!data.numcheck(txtTeacherAge.getText())){
                JOptionPane.showMessageDialog(this, "Enter valid age");
                return;
            }
            selMan.setAge(Integer.valueOf(txtTeacherAge.getText()));

            selMan.setDob(txtTeacherDOB.getText());
            if(!data.dateCheck(txtTeacherDOB.getText())){
                JOptionPane.showMessageDialog(this, "Enter valid date");
                return;
            }

            selMan.setGender(String.valueOf(cmbTeacherGender.getSelectedItem()));

            selMan.setRole(txtTeacherRole.getText());

            selMan.setEmailId(txtTeacherEmailId.getText());
            if(!data.emailCheck(txtTeacherEmailId.getText())){
                JOptionPane.showMessageDialog(this, "Enter valid emailid");
                return;
            }

            if(!data.phnocheck(txtTeacherPhno.getText())){
                JOptionPane.showMessageDialog(this, "Enter valid phone no");
                return;
            }
            selMan.setPhno(Long.valueOf(txtTeacherPhno.getText()));

            if(!data.numcheck(txtTeacherEx.getText())){
                JOptionPane.showMessageDialog(this, "Enter valid Experience");
                return;
            }
            selMan.setExperience(Integer.valueOf(txtTeacherEx.getText()));

            selMan.setPassword(txtTeacherPassword.getText());
            if(txtTeacherPassword.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Enter valid password");
                return;
            }

            JOptionPane.showMessageDialog(this, "Teacher updated successfully");

            //            dB4OUtil.storeSystem(system);
            populateTeacherTable();

        }
    }//GEN-LAST:event_btnTeacherUpdateActionPerformed

    
       private void populateTeacherTable(){
        DefaultTableModel model = (DefaultTableModel) tableTeacher.getModel();
        model.setRowCount(0);
        
//        
            for(Teacher man: system.getTeacherList().getTeacherList()){

                Object[] row = new Object[5];
                row[0] = man; 
                row[1] = man.getName();
                row[2] = man.getUsername();
                row[3] = man.getAge();
                row[4] = man.getEmailId();
                model.addRow(row);
            }
    }
    
    

    public void populateApplicationTable(){
        DefaultTableModel model = (DefaultTableModel) tableApplication.getModel();
        model.setRowCount(0);
        
//        
            for(Application man: system.getApplicationList().getApplicationList()){

                Object[] row = new Object[6];
                row[0] = man; 
                row[1] = man.getName();
                row[2] = man.getAge();
                row[3] = man.getGender();
                row[4] = man.getNgo();
                row[5] = man.getStatus();
                model.addRow(row);
            }
    }

     private void populateAppTable(){
        DefaultTableModel model = (DefaultTableModel) tableJobApp.getModel();
        model.setRowCount(0);
        
//        
            for(TeacherApply man: system.getApplist().getAppList()){

                Object[] row = new Object[5];
                row[0] = man; 
                row[1] = man.getName();
                row[2] = man.getSubject();
                row[3] = man.getEmailId();
                row[4] = man.getStatus();
                model.addRow(row);
            }
    }
     
//    public void populateCombo(){
//         
//        String[] docArr1 = system.getTeacherList().teaUsernameArray();
//        DefaultComboBoxModel dn1 = new DefaultComboBoxModel(docArr1);
//        txtStudentTeacherId.setModel(dn1);
//     }
     
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane6;
    private javax.swing.JScrollPane ScrollPaneNgoManager;
    private javax.swing.JSplitPane SplitPanePrincipal;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnAccept1;
    private javax.swing.JButton btnApplication;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnJobApp;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnReject1;
    private javax.swing.JButton btnTeacher;
    private javax.swing.JButton btnTeacherCreate;
    private javax.swing.JButton btnTeacherDelete;
    private javax.swing.JButton btnTeacherUpdate;
    private javax.swing.JButton btnTeacherView;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnView1;
    private javax.swing.JComboBox<String> cmbChildGender;
    private javax.swing.JComboBox<String> cmbTeacherGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAge1;
    private javax.swing.JLabel lblApplicationNo;
    private javax.swing.JLabel lblChildAge;
    private javax.swing.JLabel lblChildName;
    private javax.swing.JLabel lblChildName2;
    private javax.swing.JLabel lblChildName3;
    private javax.swing.JLabel lblChildName4;
    private javax.swing.JLabel lblChildName5;
    private javax.swing.JLabel lblChildName6;
    private javax.swing.JLabel lblChildName7;
    private javax.swing.JLabel lblEmailid;
    private javax.swing.JLabel lblNgoManagerId;
    private javax.swing.JLabel lblQua;
    private javax.swing.JLabel lblQua1;
    private javax.swing.JLabel lblQua2;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSchool;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatus1;
    private javax.swing.JLabel lblSub;
    private javax.swing.JLabel lblTeacherAge;
    private javax.swing.JLabel lblTeacherDOB;
    private javax.swing.JLabel lblTeacherEmailId;
    private javax.swing.JLabel lblTeacherEx;
    private javax.swing.JLabel lblTeacherGender;
    private javax.swing.JLabel lblTeacherName;
    private javax.swing.JLabel lblTeacherPassword;
    private javax.swing.JLabel lblTeacherPhno;
    private javax.swing.JLabel lblTeacherRole;
    private javax.swing.JLabel lblTeacherSearch;
    private javax.swing.JLabel lblTeacherUsername;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle5;
    private javax.swing.JLabel lblTitle7;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JLabel lblUsername2;
    private javax.swing.JPanel panelApplications;
    private javax.swing.JPanel panelControl;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelJobApply;
    private javax.swing.JPanel panelMarks;
    private javax.swing.JPanel panelTeacher;
    private javax.swing.JPanel panelWork;
    private javax.swing.JTable tableApplication;
    private javax.swing.JTable tableJobApp;
    private javax.swing.JTable tableTeacher;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAppId;
    private javax.swing.JTextField txtApplicationNo;
    private javax.swing.JTextField txtChildAge;
    private javax.swing.JTextField txtChildClass;
    private javax.swing.JTextArea txtChildComment;
    private javax.swing.JTextField txtChildDOB;
    private javax.swing.JTextField txtChildName;
    private javax.swing.JTextField txtChildSchool;
    private javax.swing.JTextArea txtComm;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtEx;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtName;
    private javax.swing.JComboBox<String> txtNgo;
    private javax.swing.JTextField txtQua;
    private javax.swing.JTextField txtSchool;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtStatus1;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JTextField txtTeacherAge;
    private javax.swing.JTextField txtTeacherDOB;
    private javax.swing.JTextField txtTeacherEmailId;
    private javax.swing.JTextField txtTeacherEx;
    private javax.swing.JTextField txtTeacherId;
    private javax.swing.JTextField txtTeacherName;
    private javax.swing.JPasswordField txtTeacherPassword;
    private javax.swing.JTextField txtTeacherPhno;
    private javax.swing.JTextField txtTeacherRole;
    private javax.swing.JTextField txtTeacherSearch;
    private javax.swing.JTextField txtTeacherUsername;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
