/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui.School;

import School.FinalResult.FinalResult;
import School.Student.Student;
import School.Teacher.Teacher;
import System.Directories.DB4OUtil;
import System.Directories.DataValidation;
import System.Directories.MainSystem;
import java.awt.CardLayout;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SrushtiGhatage
 */
public class TeacherWorkspace extends javax.swing.JPanel {

    /**
     * Creates new form TeacherWorkspace
     */
    private JPanel cardPanel;
    private Teacher teacher;
    private MainSystem system;
    private DB4OUtil dB4OUtil;
    private final String FILENAME = "ProjectDataBank.db4o";
    private DataValidation data; 
    
    public TeacherWorkspace(Teacher teacher,JPanel cardPanel, MainSystem system, DB4OUtil dB4OUtil) {
        initComponents();
        this.teacher = teacher;
        this.cardPanel = cardPanel;
        this.system = system;
        this.dB4OUtil = dB4OUtil;
        this.data = new DataValidation();
        
        populateStudentTable();
        populateStudentResTable();
        populateResultTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPaneTeacher = new javax.swing.JSplitPane();
        panelControl = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnStudent = new javax.swing.JButton();
        btnMarks = new javax.swing.JButton();
        panelWork = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        lblTitle2 = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelStudent = new javax.swing.JPanel();
        lblTitle3 = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();
        lblStudentAge = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        txtStudentAge = new javax.swing.JTextField();
        btnStudentView = new javax.swing.JButton();
        ScrollPaneNgoManager1 = new javax.swing.JScrollPane();
        tableStudent = new javax.swing.JTable();
        lblTeacherDOB1 = new javax.swing.JLabel();
        txtStudentDOB = new javax.swing.JTextField();
        lblStudentEmailId = new javax.swing.JLabel();
        txtStudentEmailId = new javax.swing.JTextField();
        txtStudentPhno = new javax.swing.JTextField();
        lblStudentPhno = new javax.swing.JLabel();
        lblStudentId = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        lblStudentSearch = new javax.swing.JLabel();
        txtStudentSearch = new javax.swing.JTextField();
        lblStudentGender = new javax.swing.JLabel();
        cmbStudentGender = new javax.swing.JComboBox<>();
        lblStudentRole = new javax.swing.JLabel();
        txtStudentRole = new javax.swing.JTextField();
        lblStudentClass = new javax.swing.JLabel();
        txtStudentClass = new javax.swing.JTextField();
        panelMarks = new javax.swing.JPanel();
        lblTitle4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableResult = new javax.swing.JTable();
        ScrollPaneNgoManager2 = new javax.swing.JScrollPane();
        tableStudentRes = new javax.swing.JTable();
        btnAutofill = new javax.swing.JButton();
        lblStudentIdRes = new javax.swing.JLabel();
        txtStudentIdRes = new javax.swing.JTextField();
        lblStudentIdRes1 = new javax.swing.JLabel();
        txtteacherIdRes = new javax.swing.JTextField();
        lblStudentNameRes = new javax.swing.JLabel();
        txtStudentNameRes = new javax.swing.JTextField();
        txtMaths = new javax.swing.JTextField();
        lblMaths = new javax.swing.JLabel();
        txtScience = new javax.swing.JTextField();
        lblScience = new javax.swing.JLabel();
        txtEnglish = new javax.swing.JTextField();
        lblEnglish = new javax.swing.JLabel();
        txtPer = new javax.swing.JTextField();
        lblPer = new javax.swing.JLabel();
        cmbResult = new javax.swing.JComboBox<>();
        lblResult = new javax.swing.JLabel();
        btnCreateRes = new javax.swing.JButton();
        lblStudentClassRes = new javax.swing.JLabel();
        txtStudentClassRes = new javax.swing.JTextField();
        btnUpdateRes = new javax.swing.JButton();
        btnDeleteRes = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMarksCard = new javax.swing.JTextArea();
        btnPrint = new javax.swing.JButton();

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnStudent.setText("Student");
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });

        btnMarks.setText("Final Result");
        btnMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelControlLayout = new javax.swing.GroupLayout(panelControl);
        panelControl.setLayout(panelControlLayout);
        panelControlLayout.setHorizontalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelControlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(btnStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(btnMarks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelControlLayout.setVerticalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(btnHome)
                .addGap(18, 18, 18)
                .addComponent(btnStudent)
                .addGap(18, 18, 18)
                .addComponent(btnMarks)
                .addContainerGap(465, Short.MAX_VALUE))
        );

        SplitPaneTeacher.setLeftComponent(panelControl);

        panelWork.setLayout(new java.awt.CardLayout());

        panelHome.setLayout(null);

        lblTitle2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("School");
        panelHome.add(lblTitle2);
        lblTitle2.setBounds(0, 6, 1300, 32);

        lblRole.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblRole.setText("Role: Teacher");
        panelHome.add(lblRole);
        lblRole.setBounds(1091, 95, 139, 16);

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        panelHome.add(btnLogOut);
        btnLogOut.setBounds(1091, 117, 73, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/teaher workspace.gif"))); // NOI18N
        panelHome.add(jLabel1);
        jLabel1.setBounds(60, 50, 990, 640);

        panelWork.add(panelHome, "card2");

        lblTitle3.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        lblTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle3.setText("Student");

        lblStudentName.setText("Name:");

        lblStudentAge.setText("Age:");

        btnStudentView.setText("View");
        btnStudentView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentViewActionPerformed(evt);
            }
        });

        tableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Class", "Age", "Email-Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ScrollPaneNgoManager1.setViewportView(tableStudent);

        lblTeacherDOB1.setText("DOB:");

        lblStudentEmailId.setText("Email-Id:");

        lblStudentPhno.setText("Phone No:");

        lblStudentId.setText("Student Id:");

        lblStudentSearch.setText("Search:");

        lblStudentGender.setText("Gender:");

        cmbStudentGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));

        lblStudentRole.setText("Role:");

        txtStudentRole.setEditable(false);
        txtStudentRole.setText("Student");

        lblStudentClass.setText("Class:");

        javax.swing.GroupLayout panelStudentLayout = new javax.swing.GroupLayout(panelStudent);
        panelStudent.setLayout(panelStudentLayout);
        panelStudentLayout.setHorizontalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelStudentLayout.createSequentialGroup()
                        .addComponent(lblStudentSearch)
                        .addGap(18, 18, 18)
                        .addComponent(txtStudentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnStudentView)
                        .addComponent(ScrollPaneNgoManager1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(303, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStudentId)
                    .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelStudentLayout.createSequentialGroup()
                            .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelStudentLayout.createSequentialGroup()
                                    .addComponent(lblStudentName)
                                    .addGap(21, 21, 21))
                                .addGroup(panelStudentLayout.createSequentialGroup()
                                    .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblStudentRole)
                                        .addComponent(lblTeacherDOB1))
                                    .addGap(30, 30, 30)))
                            .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtStudentDOB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelStudentLayout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtStudentAge, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(txtStudentRole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txtStudentClass, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelStudentLayout.createSequentialGroup()
                            .addComponent(lblStudentClass)
                            .addGap(277, 277, 277)))
                    .addGroup(panelStudentLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblStudentAge)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStudentPhno)
                    .addComponent(lblStudentEmailId)
                    .addComponent(lblStudentGender))
                .addGap(38, 38, 38)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStudentPhno, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbStudentGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtStudentEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(lblTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelStudentLayout.setVerticalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTitle3)
                .addGap(72, 72, 72)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentSearch)
                    .addComponent(txtStudentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPaneNgoManager1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStudentView)
                .addGap(54, 54, 54)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStudentLayout.createSequentialGroup()
                        .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentId)
                            .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStudentGender))
                        .addGap(18, 18, 18)
                        .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelStudentLayout.createSequentialGroup()
                                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblStudentName))
                                .addGap(18, 18, 18)
                                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStudentAge)
                                    .addComponent(txtStudentAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelStudentLayout.createSequentialGroup()
                                .addComponent(lblStudentEmailId)
                                .addGap(18, 18, 18)
                                .addComponent(lblStudentPhno)
                                .addGap(18, 18, 18)
                                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtStudentDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTeacherDOB1))))
                        .addGap(20, 20, 20)
                        .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStudentRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStudentRole))
                        .addGap(18, 18, 18)
                        .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStudentClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStudentClass)))
                    .addGroup(panelStudentLayout.createSequentialGroup()
                        .addComponent(cmbStudentGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtStudentEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtStudentPhno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        panelWork.add(panelStudent, "card2");

        panelMarks.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle4.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        lblTitle4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle4.setText("Final Result");

        tableResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student Id", "Student Name", "Class", "Maths", "Science", "English", "Percentage", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableResult);

        tableStudentRes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Class", "Age", "Email-Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableStudentRes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ScrollPaneNgoManager2.setViewportView(tableStudentRes);

        btnAutofill.setText("Autofill");
        btnAutofill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutofillActionPerformed(evt);
            }
        });

        lblStudentIdRes.setText("Student Id:");

        txtStudentIdRes.setEditable(false);
        txtStudentIdRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentIdResActionPerformed(evt);
            }
        });

        lblStudentIdRes1.setText("Teacher Id:");

        txtteacherIdRes.setEditable(false);
        txtteacherIdRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteacherIdResActionPerformed(evt);
            }
        });

        lblStudentNameRes.setText("Student Name:");

        txtStudentNameRes.setEditable(false);
        txtStudentNameRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNameResActionPerformed(evt);
            }
        });

        txtMaths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMathsActionPerformed(evt);
            }
        });

        lblMaths.setText("Maths:");

        txtScience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScienceActionPerformed(evt);
            }
        });

        lblScience.setText("Science:");

        txtEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnglishActionPerformed(evt);
            }
        });

        lblEnglish.setText("English:");

        txtPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerActionPerformed(evt);
            }
        });

        lblPer.setText("Percentage:");

        cmbResult.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pass", "Fail" }));

        lblResult.setText("Result:");

        btnCreateRes.setText("Create");
        btnCreateRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateResActionPerformed(evt);
            }
        });

        lblStudentClassRes.setText("Class:");

        txtStudentClassRes.setEditable(false);
        txtStudentClassRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentClassResActionPerformed(evt);
            }
        });

        btnUpdateRes.setText("Update");
        btnUpdateRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateResActionPerformed(evt);
            }
        });

        btnDeleteRes.setText("Delete");
        btnDeleteRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteResActionPerformed(evt);
            }
        });

        txtMarksCard.setColumns(20);
        txtMarksCard.setRows(5);
        txtMarksCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(txtMarksCard);

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMarksLayout = new javax.swing.GroupLayout(panelMarks);
        panelMarks.setLayout(panelMarksLayout);
        panelMarksLayout.setHorizontalGroup(
            panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle4, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
            .addGroup(panelMarksLayout.createSequentialGroup()
                .addGroup(panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelMarksLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMarksLayout.createSequentialGroup()
                                .addComponent(lblStudentIdRes1)
                                .addGap(18, 18, 18)
                                .addComponent(txtteacherIdRes, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMarksLayout.createSequentialGroup()
                                .addComponent(lblStudentIdRes)
                                .addGap(18, 18, 18)
                                .addComponent(txtStudentIdRes, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelMarksLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelMarksLayout.createSequentialGroup()
                                .addComponent(lblPer)
                                .addGap(18, 18, 18)
                                .addComponent(txtPer, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMarksLayout.createSequentialGroup()
                                .addGroup(panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEnglish)
                                    .addComponent(lblScience)
                                    .addGroup(panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblStudentClassRes)
                                        .addComponent(lblMaths)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStudentClassRes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaths, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtScience, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEnglish, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelMarksLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblStudentNameRes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtStudentNameRes, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelMarksLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblResult)
                        .addGap(26, 26, 26)
                        .addComponent(cmbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(379, 379, 379))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMarksLayout.createSequentialGroup()
                        .addGroup(panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMarksLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(btnCreateRes, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdateRes, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteRes, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMarksLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMarksLayout.createSequentialGroup()
                                        .addComponent(btnPrint)
                                        .addGap(150, 150, 150)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(panelMarksLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAutofill)
                    .addGroup(panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                        .addComponent(ScrollPaneNgoManager2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMarksLayout.setVerticalGroup(
            panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMarksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle4)
                .addGap(34, 34, 34)
                .addComponent(ScrollPaneNgoManager2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAutofill)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelMarksLayout.createSequentialGroup()
                        .addGroup(panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentIdRes)
                            .addComponent(txtStudentIdRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblResult))
                        .addGap(18, 18, 18)
                        .addGroup(panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentIdRes1)
                            .addComponent(txtteacherIdRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStudentNameRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStudentNameRes))
                        .addGap(18, 18, 18)
                        .addGroup(panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStudentClassRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStudentClassRes))
                        .addGap(18, 18, 18)
                        .addGroup(panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaths))
                        .addGap(18, 18, 18)
                        .addGroup(panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtScience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblScience))
                        .addGap(18, 18, 18)
                        .addGroup(panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEnglish))
                        .addGap(18, 18, 18)
                        .addGroup(panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPer)))
                    .addGroup(panelMarksLayout.createSequentialGroup()
                        .addGroup(panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCreateRes)
                            .addComponent(btnUpdateRes)
                            .addComponent(btnDeleteRes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnPrint)
                .addContainerGap())
        );

        panelWork.add(panelMarks, "card4");

        SplitPaneTeacher.setRightComponent(panelWork);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneTeacher)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneTeacher)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        panelWork.removeAll();
        panelWork.add(panelHome);
        panelWork.repaint();
        panelWork.revalidate();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnStudentViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentViewActionPerformed
        // TODO add your handling code here:
        Integer selectedRowIndex = tableStudent.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableStudent.getModel();
            Student selMan = (Student) model.getValueAt(selectedRowIndex,0);

            txtStudentId.setText(selMan.getStudentId());
            txtStudentName.setText(selMan.getName());

            txtStudentAge.setText(String.valueOf(selMan.getAge()));
            txtStudentDOB.setText(selMan.getDob());
            cmbStudentGender.setSelectedItem(selMan.getGender());
            txtStudentRole.setText(selMan.getRole());
            txtStudentClass.setText(selMan.getCls());
            txtStudentEmailId.setText(selMan.getEmailId());
            txtStudentPhno.setText(String.valueOf(selMan.getPhno()));

        }
    }//GEN-LAST:event_btnStudentViewActionPerformed

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        // TODO add your handling code here:
        panelWork.removeAll();
        panelWork.add(panelStudent);
        panelWork.repaint();
        panelWork.revalidate();
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        dB4OUtil.storeSystem(system);
        CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
        cardPanel.remove(this);
        cardLayout.previous(cardPanel);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarksActionPerformed
        // TODO add your handling code here:
        panelWork.removeAll();
        panelWork.add(panelMarks);
        panelWork.repaint();
        panelWork.revalidate();
        
    }//GEN-LAST:event_btnMarksActionPerformed

    private void btnAutofillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutofillActionPerformed
        // TODO add your handling code here
        Integer selectedRowIndex = tableStudentRes.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableStudentRes.getModel();
            Student selApp = (Student) model.getValueAt(selectedRowIndex,0);

            //            txtApplicationNo.setText(selApp.getAppNo());
            txtStudentIdRes.setText(selApp.getStudentId());
            txtStudentNameRes.setText(selApp.getName());
            txtteacherIdRes.setText(selApp.getTeachId());
            txtStudentClassRes.setText(selApp.getCls());
           
            //            txtChildClass.setText(selApp.getCls());
            //            txtStatus.setText(selApp.getStatus());
            //            txtChildComment.setText(selApp.getComment());
        }
    }//GEN-LAST:event_btnAutofillActionPerformed

    private void txtStudentIdResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentIdResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIdResActionPerformed

    private void txtteacherIdResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteacherIdResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteacherIdResActionPerformed

    private void txtStudentNameResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNameResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNameResActionPerformed

    private void txtMathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMathsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMathsActionPerformed

    private void txtScienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScienceActionPerformed

    private void txtEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnglishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnglishActionPerformed

    private void txtPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerActionPerformed

    private void txtStudentClassResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentClassResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentClassResActionPerformed

    private void btnCreateResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateResActionPerformed
        // TODO add your handling code here:
        String stId = txtStudentIdRes.getText();
        String name = txtStudentNameRes.getText();
        String teId = txtteacherIdRes.getText();
        String cls = txtStudentClassRes.getText();
        
        if(!data.numcheck(txtMaths.getText())){
            JOptionPane.showMessageDialog(this, "Enter valid age");
            return;
	}
        Integer math = Integer.valueOf(txtMaths.getText());
        
        if(!data.numcheck(txtScience.getText())){
            JOptionPane.showMessageDialog(this, "Enter valid age");
            return;
	}
        Integer sci = Integer.valueOf(txtScience.getText());
        
        if(!data.numcheck(txtEnglish.getText())){
            JOptionPane.showMessageDialog(this, "Enter valid age");
            return;
	}
        Integer eng = Integer.valueOf(txtEnglish.getText());
        
        if(!data.numcheck(txtPer.getText())){
            JOptionPane.showMessageDialog(this, "Enter valid age");
            return;
	}
        Integer percent = Integer.valueOf(txtPer.getText());
        
        
        String res = String.valueOf(cmbResult.getSelectedItem());
        
        FinalResult newRes = system.getResList().addFinalResult();
        
        newRes.setStudentId(stId);
        newRes.setName(name);
        newRes.setTeachId(teId);
        newRes.setCls(cls);
        newRes.setMath(math);
        newRes.setScience(sci);
        newRes.setEnglish(eng);
        newRes.setPercent(percent);
        newRes.setResult(res);
        
        populateResultTable();
        
        
        txtMarksCard.append("\t\t Report Card \n\n"+
                "Student Id: \t\t\t" + txtStudentIdRes.getText()+ "\n\n"+
                "Student Name: \t\t\t"+ txtStudentNameRes.getText()+ "\n\n"+
                "Class: \t\t\t"+ txtStudentClassRes.getText()+ "\n\n"+
                "\n==============================================================\n"+
                "Maths: \t\t\t"+ txtMaths.getText()+ "\n\n"+
                "Science: \t\t\t"+ txtScience.getText()+ "\n\n"+
                "English: \t\t\t"+ txtEnglish.getText()+ "\n\n"+
                "\n--------------------------------------------------------------\n"+
                "Percentage: \t\t\t"+ txtPer.getText()+ "%\n\n"+
                "Result: \t\t\t"+ cmbResult.getSelectedItem()+ "\n\n"+
                "\n=========================================================\n"
        );
                
    }//GEN-LAST:event_btnCreateResActionPerformed

    private void btnUpdateResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateResActionPerformed
        // TODO add your handling code here:
        Integer selectedRowIndex = tableResult.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableResult.getModel();
            FinalResult selRes = (FinalResult) model.getValueAt(selectedRowIndex,0);
            
            if(!data.numcheck(txtMaths.getText())){
		JOptionPane.showMessageDialog(this, "Enter valid Nath score");
                return;
            }
            selRes.setMath(Integer.valueOf(txtMaths.getText()));
            
            
            if(!data.numcheck(txtScience.getText())){
		JOptionPane.showMessageDialog(this, "Enter Science score");
                return;
            }
            selRes.setScience(Integer.valueOf(txtScience.getText()));
            
            
            if(!data.numcheck(txtEnglish.getText())){
                JOptionPane.showMessageDialog(this, "Enter English  score");
                return;
            }
            selRes.setEnglish(Integer.valueOf(txtEnglish.getText()));
            
            
            if(!data.numcheck(txtPer.getText())){
		JOptionPane.showMessageDialog(this, "Enter Percentage");
                return;
            }
            selRes.setPercent(Integer.valueOf(txtPer.getText()));
            
            
            selRes.setResult(String.valueOf(cmbResult.getSelectedItem()));
            
            populateResultTable();
        }
            
        
    }//GEN-LAST:event_btnUpdateResActionPerformed

    private void btnDeleteResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteResActionPerformed
        // TODO add your handling code here:
        Integer selectedRowIndex = tableResult.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableResult.getModel();
            FinalResult selectedMan = (FinalResult) model.getValueAt(selectedRowIndex,0);

            system.getResList().deleteFinalResult(selectedMan);

            JOptionPane.showMessageDialog(this, "Result record deleted successfully.");
            
//            dB4OUtil.storeSystem(system);
            populateResultTable();
        }
    }//GEN-LAST:event_btnDeleteResActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try {
            // TODO add your handling code here:
            txtMarksCard.print();
        } catch (PrinterException ex) {
            Logger.getLogger(TeacherWorkspace.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void populateStudentTable(){
        DefaultTableModel model = (DefaultTableModel) tableStudent.getModel();
        model.setRowCount(0);
        
//        
            for(Student man: system.getStudentList().getStudentList()){
                if(man.getTeachId().equals(teacher.getUsername())){
                    Object[] row = new Object[5];
                    row[0] = man; 
                    row[1] = man.getName();
                    row[2] = man.getCls();
                    row[3] = man.getAge();
                    row[4] = man.getEmailId();
                    model.addRow(row);
                }
            }
    }
    
    private void populateStudentResTable(){
        DefaultTableModel model = (DefaultTableModel) tableStudentRes.getModel();
        model.setRowCount(0);
        
//        
            for(Student man: system.getStudentList().getStudentList()){
                if(man.getTeachId().equals(teacher.getUsername())){
                    Object[] row = new Object[5];
                    row[0] = man; 
                    row[1] = man.getName();
                    row[2] = man.getCls();
                    row[3] = man.getAge();
                    row[4] = man.getEmailId();
                    model.addRow(row);
                }
            }
    }
    
    private void populateResultTable(){
        DefaultTableModel model = (DefaultTableModel) tableResult.getModel();
        model.setRowCount(0);
        
//        
            for(FinalResult man: system.getResList().getResultList()){

                Object[] row = new Object[8];
                row[0] = man; 
                row[1] = man.getName();
                row[2] = man.getCls();
                row[3] = man.getMath();
                row[4] = man.getScience();
                row[5] = man.getEnglish();
                row[6] = man.getPercent();
                row[7] = man.getResult();
                model.addRow(row);
            }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPaneNgoManager1;
    private javax.swing.JScrollPane ScrollPaneNgoManager2;
    private javax.swing.JSplitPane SplitPaneTeacher;
    private javax.swing.JButton btnAutofill;
    private javax.swing.JButton btnCreateRes;
    private javax.swing.JButton btnDeleteRes;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMarks;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnStudent;
    private javax.swing.JButton btnStudentView;
    private javax.swing.JButton btnUpdateRes;
    private javax.swing.JComboBox<String> cmbResult;
    private javax.swing.JComboBox<String> cmbStudentGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEnglish;
    private javax.swing.JLabel lblMaths;
    private javax.swing.JLabel lblPer;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblScience;
    private javax.swing.JLabel lblStudentAge;
    private javax.swing.JLabel lblStudentClass;
    private javax.swing.JLabel lblStudentClassRes;
    private javax.swing.JLabel lblStudentEmailId;
    private javax.swing.JLabel lblStudentGender;
    private javax.swing.JLabel lblStudentId;
    private javax.swing.JLabel lblStudentIdRes;
    private javax.swing.JLabel lblStudentIdRes1;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblStudentNameRes;
    private javax.swing.JLabel lblStudentPhno;
    private javax.swing.JLabel lblStudentRole;
    private javax.swing.JLabel lblStudentSearch;
    private javax.swing.JLabel lblTeacherDOB1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JPanel panelControl;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelMarks;
    private javax.swing.JPanel panelStudent;
    private javax.swing.JPanel panelWork;
    private javax.swing.JTable tableResult;
    private javax.swing.JTable tableStudent;
    private javax.swing.JTable tableStudentRes;
    private javax.swing.JTextField txtEnglish;
    private javax.swing.JTextArea txtMarksCard;
    private javax.swing.JTextField txtMaths;
    private javax.swing.JTextField txtPer;
    private javax.swing.JTextField txtScience;
    private javax.swing.JTextField txtStudentAge;
    private javax.swing.JTextField txtStudentClass;
    private javax.swing.JTextField txtStudentClassRes;
    private javax.swing.JTextField txtStudentDOB;
    private javax.swing.JTextField txtStudentEmailId;
    private javax.swing.JTextField txtStudentId;
    private javax.swing.JTextField txtStudentIdRes;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtStudentNameRes;
    private javax.swing.JTextField txtStudentPhno;
    private javax.swing.JTextField txtStudentRole;
    private javax.swing.JTextField txtStudentSearch;
    private javax.swing.JTextField txtteacherIdRes;
    // End of variables declaration//GEN-END:variables
}
