/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui.LoginPage;

import Funding.FundManager.FundManager;
import Funding.PublicUser.PublicUser;
import System.Directories.DB4OUtil;
import System.Directories.MainSystem;
import Ui.Ngo.FundManagerWorkspace;
import Ui.Ngo.PublicUserRegister;
import Ui.Ngo.PublicUserWorkspace;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author megha
 */
public class FundingLoginPage extends javax.swing.JPanel {

    /**
     * Creates new form FundingLoginPage
     */
    private JPanel cardPanel;
    private MainSystem system;
    private DB4OUtil dB4OUtil;
    
    public FundingLoginPage(JPanel cardPanel, MainSystem system, DB4OUtil dB4OUtil) {
        initComponents();
        this.cardPanel = cardPanel;
        this.system = system;
        this.dB4OUtil = dB4OUtil;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        lblRole = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        btnLogin = new javax.swing.JButton();
        btnReg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Login Page");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 388, -1));

        btnBack.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 230, 30));

        lblUsername.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username:");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        lblPass.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblPass.setForeground(new java.awt.Color(255, 255, 255));
        lblPass.setText("Password:");
        add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 100, 30));
        add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 230, 30));

        lblRole.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblRole.setForeground(new java.awt.Color(255, 255, 255));
        lblRole.setText("Role:");
        add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        cmbRole.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fund Manager", "Public User" }));
        add(cmbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 361, 230, 30));

        btnLogin.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));

        btnReg.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnReg.setText("Register");
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });
        add(btnReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/donation.gif"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 1300, 750));

        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 420, 220));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
        cardPanel.remove(this);
        cardLayout.previous(cardPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        String username = txtUsername.getText();
        String password = txtPass.getText();
        String role = String.valueOf(cmbRole.getSelectedItem());
        FundManager fundManager = system.getFundManagerList().findFundManager(username, password);
        PublicUser user = system.getPublicUserList().findPublicUser(username, password);

        try{
//            if(role.equals("Fund Manager")){
            if(role.equals("Fund Manager")&&(username.equals("Admin") && password.equals("pass"))){
                    FundManagerWorkspace ngoManJPanel = new FundManagerWorkspace(fundManager,cardPanel, system, dB4OUtil);
                    CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
                    cardPanel.add("FundManagerJPanel",ngoManJPanel);
                    cardLayout.next(cardPanel);
                }
//            }
//            else if(role.equals("Public User")){
             else if(role.equals("Public User")&&(username.equals(user.getUsername()) && password.equals(user.getPassword()))){
                    PublicUserWorkspace publicUserJPanel = new PublicUserWorkspace(user,cardPanel, system, dB4OUtil);
                    CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
                    cardPanel.add("publicUserJPanel",publicUserJPanel);
                    cardLayout.next(cardPanel);
                }
//            }
            else{
                JOptionPane.showMessageDialog(this, "Please enter the correct username and password and role.");
            }
        }
        catch(NullPointerException n){
            JOptionPane.showMessageDialog(this, "Please enter the correct username and password and role.");
        }
        
        txtUsername.setText("");
        txtPass.setText("");
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        // TODO add your handling code here:
        PublicUserRegister userRegJPanel = new PublicUserRegister(cardPanel, system, dB4OUtil);
        CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
        cardPanel.add("userRegisterPanel", userRegJPanel);
        cardLayout.next(cardPanel);
    }//GEN-LAST:event_btnRegActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnReg;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
