/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui.LoginPage;

import Pharmacy.DeliveryMan.DeliveryMan;
import Pharmacy.Pharmacist.Pharmacist;
import System.Directories.DB4OUtil;
import System.Directories.MainSystem;
import Ui.MedStore.DeliveryManWorkspace;
import Ui.MedStore.MedAdminWorkspace;
import Ui.MedStore.PharmacistWorkspace;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author megha
 */
public class MedStoreLoginPage extends javax.swing.JPanel {

    /**
     * Creates new form MedStoreLoginPage
     */
    private JPanel cardPanel;
    private MainSystem system;
    private DB4OUtil dB4OUtil;
    
    public MedStoreLoginPage(JPanel cardPanel, MainSystem system, DB4OUtil dB4OUtil) {
        initComponents();
        this.cardPanel = cardPanel;
        this.system = system;
        this.dB4OUtil = dB4OUtil;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        lblUsername = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(44, 75, 72, 23);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Login Page");
        add(lblTitle);
        lblTitle.setBounds(0, 6, 800, 32);
        add(txtUsername);
        txtUsername.setBounds(294, 170, 222, 22);
        add(txtPass);
        txtPass.setBounds(291, 232, 224, 22);

        lblUsername.setText("Username:");
        add(lblUsername);
        lblUsername.setBounds(164, 170, 112, 19);

        lblPass.setText("Password:");
        add(lblPass);
        lblPass.setBounds(221, 235, 53, 16);

        lblRole.setText("Role:");
        add(lblRole);
        lblRole.setBounds(221, 294, 26, 16);

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MedStore Admin", "Pharmacist", "Delivery Man" }));
        add(cmbRole);
        cmbRole.setBounds(292, 291, 224, 22);

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        add(btnLogin);
        btnLogin.setBounds(331, 394, 61, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/medstore.gif"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 80, 870, 550);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
        cardPanel.remove(this);
        cardLayout.previous(cardPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        String username = txtUsername.getText();
        String password = txtPass.getText();
        String role = String.valueOf(cmbRole.getSelectedItem());
        Pharmacist pharm = system.getPharmlist().findPharmacist(username, password);
        DeliveryMan delMan = system.getDeliveryManlist().findDeliveryMan(username, password);

        try{
//            if(role.equals("MedStore Admin")){
            if(role.equals("MedStore Admin")&&(username.equals("Admin") && password.equals("pass"))){
                    MedAdminWorkspace adminJPanel = new MedAdminWorkspace(cardPanel, system, dB4OUtil);
                    CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
                    cardPanel.add("adminJPanel",adminJPanel);
                    cardLayout.next(cardPanel);
                }
//            }
//            else if(role.equals("Pharmacist")){
            else if(role.equals("Pharmacist")&&(username.equals(pharm.getUsername()) && password.equals(pharm.getPassword()))){
                    PharmacistWorkspace ngoManJPanel = new PharmacistWorkspace(pharm,cardPanel, system, dB4OUtil);
                    CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
                    cardPanel.add("ngoManagerJPanel",ngoManJPanel);
                    cardLayout.next(cardPanel);
                }
//            }
//            else if(role.equals("Delivery Man")){
            else if(role.equals("Delivery Man")&&(username.equals(delMan.getUsername()) && password.equals(delMan.getPassword()))){
                    DeliveryManWorkspace caretakerJPanel = new DeliveryManWorkspace(delMan,cardPanel, system, dB4OUtil);
                    CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
                    cardPanel.add("caretakerJPanel",caretakerJPanel);
                    cardLayout.next(cardPanel);
                }
//            }
            else{
                JOptionPane.showMessageDialog(this, "Please enter the correct username and password and role.");
            }
        }
        catch(NullPointerException n){
            JOptionPane.showMessageDialog(this, "Please enter the correct username and password and role.");
        }

        txtUsername.setText("");
        txtPass.setText("");
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
